apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          lifecycle:
            postStart:
              exec:
                command: ["apk", "add", "git"]
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGO_PASSWORD
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGO_DATABASE
            - name: PORT_API
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: PORT_API
            - name: ALLOWED_URI
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: ALLOWED_URI
            - name: URL_API
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: URL_API
            - name: URL_APP
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: URL_APP
            - name: GOOGLE_OAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: GOOGLE_OAUTH_URL
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GITEA_URL
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: GITEA_URL
            - name: GITEA_ADMIN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: GITEA_ADMIN_ACCESS_TOKEN
            - name: SESSION_NAME
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: SESSION_NAME
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: be-secrets
                  key: SESSION_SECRET
            - name: BE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: be-token
                  key: BE_TOKEN
            - name: JENKINS_URL
              valueFrom:
                secretKeyRef:
                  name: jenkins-url
                  key: JENKINS_URL
            - name: JENKINS_SC_NAME
              valueFrom:
                secretKeyRef:
                  name: jenkins-token
                  key: name
            - name: JENKINS_SC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jenkins-token
                  key: JENKINS_SC_TOKEN
            - name: MONGO_SERVICE
              value: "mongodb.default.svc.cluster.local"
            - name: BASE_PATH
              value: "/server"
            - name: MONGO_PORT
              value: "27017"
            - name: API_BASE_URL
              value: "http://bawix.xyz:81/api/v2"
            - name: USER_ADMIN_NAME
              valueFrom:
                secretKeyRef:
                  name: user-admin-access
                  key: NAME
            - name: USER_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: user-admin-access
                  key: PASSWORD
            - name: USER_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: user-admin-access
                  key: EMAIl
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
